spring:
  datasource:
    url: jdbc:mysql://db:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: reader
    password: 123456
  data:
    elasticsearch:
      cluster-nodes: es:9300
      cluster-name: elasticsearch
logging:
  path: /var/logs #配置日志生成路径